Integration of Uint8_t array control in Serialization
Mesh4all/m4a-firmware pull request #131
Opened 2022-02-05 01:16 UTC by eduazocar

### Contribution description

This Pull request referred to control to encode and decode arrays of bytes and data type uint8_t. In these changes could see that decode implement a void pointer, that could be help to manipulate other data types and check every one if is that type. So, this can be util to avoid build somes functions to encode and decode... The main proposal is to control it with only a function encode and one function decode... Well, there is some close to upgrade for another cases.

### Testing procedure

### Issues/PRs references

Fixes #129

2022-02-07 18:44 UTC, xkevin190 requested changes

2022-02-07 18:44 UTC, xkevin190 commented on wifi-subsys/components/tools/test/test_cbor.c
> +
remove space in else

2022-02-07 18:44 UTC, xkevin190 commented on wifi-subsys/components/tools/test/test_cbor.c
> +
equal here

2022-02-07 18:44 UTC, xkevin190 commented on wifi-subsys/components/tools/test/test_cbor.c
> +    {
incorrect format  
```suggestion
    if () {
    }
```

2022-02-07 18:59 UTC, luisan00 commented on wifi-subsys/components/tools/src/serialization.c
> +        ESP_LOGE(TAG, "Error creating map");
also printing code error here can be usable

2022-02-07 19:00 UTC, luisan00 commented on wifi-subsys/components/tools/src/serialization.c
> +        ESP_LOGE(TAG, "Wrong passing string bytes");
the same as before

2022-02-07 19:02 UTC, luisan00 requested changes
Round 1

2022-02-08 12:55 UTC, luisan00 commented
Please @eduazocar @xkevin190  check the unresolved conversations

2022-02-08 13:45 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +    TEST_FAIL();
log it

2022-02-08 13:45 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +    TEST_FAIL();
log it

2022-02-08 13:45 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +    TEST_FAIL();
log it

2022-02-08 14:06 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +  ESP_LOGI("The value received is ", "%lld", (long long)val_received);
one line

2022-02-08 14:08 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +  ESP_LOGI("The value received is ", "%lld", (long long)val_received);
one single log

2022-02-08 14:09 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +  ESP_LOGI("The value received is ", "%lld", (long long)val_received);
one single line

2022-02-08 19:52 UTC, luisan00 requested changes
Wrong indentation, use 4 spaces not 2 spaces

2022-02-08 22:29 UTC, luisan00 commented on wifi-subsys/components/tools/test/test_cbor.c
> +        ESP_LOGD(__func__, "Reason %s, No(%d)", esp_err_to_name(err), err);
```suggestion
        ESP_LOGE(TAG, "Reason %s, No(%d)", esp_err_to_name(err), err);
```
TAG can be some kind of identifier such as "TEST",  "CBOR_TEST" or similar.

Don't use debug logging in this PR

2022-02-08 22:33 UTC, luisan00 requested changes
Use the indicated logging format on each LOG error and don't use debug logging in this PR.

2022-02-08 22:34 UTC, luisan00 commented
Also the commit msg need to be changed

2022-02-09 15:22 UTC, luisan00 reviewed
looks good for me, some request @xkevin190 or @RocioRojas ?

2022-02-09 15:56 UTC, luisan00 commented
@xkevin190 ?

2022-02-09 15:59 UTC, xkevin190 requested changes

2022-02-09 15:59 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +#include <stdio.h>
move this to the top.

2022-02-09 16:20 UTC, xkevin190 requested changes

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +        ESP_LOGE(TAG, "Error creating map, Error #%d ", err);
remove the TAG

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
>      ESP_LOG_BUFFER_HEXDUMP(TAG, cbor_coded, *len, ESP_LOG_INFO);
remove the TAG

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +            ESP_LOGE(TAG, "Error Opening map, Error #%d ", err);
remove the TAG and add the esp_err_to_name for indentify the error better

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +            ESP_LOGE(TAG, "Data and owner not founded %d", err);
remove the TAG and add the esp_err_to_name for indentify the error better

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +        ESP_LOGE(TAG, "Error creating map, Error #%d ", err);
remove the TAG and add the esp_err_to_name for indentify the error better

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +        ESP_LOGE(TAG, "Wrong passing string bytes, Error #%d ", err);
remove the TAG and add the esp_err_to_name for indentify the error better

2022-02-09 16:20 UTC, xkevin190 commented on wifi-subsys/components/tools/src/serialization.c
> +    ESP_LOG_BUFFER_HEXDUMP(TAG, cbor_coded, *len, ESP_LOG_INFO);
remove the TAG

2022-02-09 18:23 UTC, xkevin190 approved these changes

2022-02-09 18:24 UTC, xkevin190 commented
this PR is ok for me.

2022-02-09 19:06 UTC, luisan00 approved these changes

2022-02-09 19:31 UTC, merged