icmp_ping
Mesh4all/m4a-firmware pull request #146
Opened 2022-02-17 19:10 UTC by RocioRojas

### Contribution description
Add milliseconds between each ping procedure
Add a “ping” session contains count procedures
Delete vTaskDelay

### Testing procedure
look at wifi-subsys/components/protocols/icmp_ping.c
- esp_ping_confing_t struct
look at wifi-subsys/main/default_params.h
- #define PING_TIME 5000                                /* Milliseconds between each ping procedure*/
  #define PING_RETRIES 3                                /* A “ping” session contains count procedures*/

 Fixes #144

2022-02-18 15:15 UTC, xkevin190 approved these changes

2022-02-18 15:15 UTC, xkevin190 commented on wifi-subsys/components/protocols/src/icmp_ping.c
> +        int result = getaddrinfo(&url, NULL, &hint, &res);
bad identation 
```suggestion
    if (err != ESP_OK) {
        ESP_LOGE(__func__,
                "error to get url the cause is %s",
                esp_err_to_name(err));

        return err;
    }
    int result = getaddrinfo(&url, NULL, &hint, &res);
```

2022-02-18 15:15 UTC, xkevin190 commented on wifi-subsys/components/protocols/src/icmp_ping.c
> +        printf("Initializing ping");
change this por esp_logi please i know is not your change, but seems we not see this printf when check icmp PR

2022-02-18 15:25 UTC, xkevin190 requested changes

2022-02-18 15:25 UTC, xkevin190 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    esp_err_t err = set_default_credentials();
you don't this remove please.

2022-02-18 15:25 UTC, xkevin190 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    esp_err_t err = set_default_credentials();
change `set_default_credentials` for  `set_default_ping_settings`  i think you don't need this or yes?

2022-02-18 15:25 UTC, xkevin190 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    };
```suggestion
     err = set_default_credentials();
     if (err != ESP_OK) {
        TEST_FAIL();
    };
    err = wifi_init();
    if (err != ESP_OK) {
        TEST_FAIL();
    };
   
  
```

2022-02-18 15:25 UTC, xkevin190 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +     esp_err_t err = set_default_credentials();
check identation

2022-02-18 21:42 UTC, xkevin190 requested changes

2022-02-19 08:20 UTC, luisan00 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    {
looks like the format of some structures is wrong

2022-02-19 08:20 UTC, luisan00 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    if (err != ESP_OK)
here too

2022-02-19 08:23 UTC, luisan00 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    }
indentation ...

2022-02-19 08:24 UTC, luisan00 commented on wifi-subsys/components/protocols/test/test_icmp.c
> +    if (err != ESP_OK)
looks like you are not using the clang format tool correctly

2022-02-21 14:03 UTC, xkevin190 requested changes

2022-02-21 14:03 UTC, xkevin190 commented on wifi-subsys/components/protocols/src/icmp_ping.c
> +
identation error

2022-02-21 14:03 UTC, xkevin190 commented on wifi-subsys/components/protocols/src/icmp_ping.c
> +        ESP_LOGE(__func__, "error to get ping count the cause is %s",
identation error

2022-02-21 14:03 UTC, xkevin190 commented on wifi-subsys/components/protocols/src/icmp_ping.c
> +        ESP_LOGE(__func__, "Error to the init ping session %s",
identation error

2022-02-21 15:01 UTC, xkevin190 approved these changes

2022-02-21 15:37 UTC, xkevin190 approved these changes

2022-02-21 15:54 UTC, luisan00 commented
Squash and ready to go ahead 👍

2022-02-21 16:05 UTC, merged