example: at_uart
Mesh4all/m4a-firmware pull request #155
Opened 2022-02-23 06:15 UTC by RocioRojas

### Contribution description
Sends at commands using uart from samr21 to esp32 

### Testing procedure
Look at /home/usuario/esp/gitnuevo/m4a-firmware/examples/at_uart
use in shell make BOARD=samr21-xpro flash term
use at help
```  
// shell command, value description, at command, argument
    {"wap_ssid", "<AP SSID>", "AT+WAP_SSID=", 1},
    {"wap_pass", "<AP Password>", "AT+WAP_PASS=", 1},
    {"wsta_ssid", "<STA SSID>", "AT+WSTA_SSID=", 1},
    {"wsta_pass", "<STA Password>", "AT+WSTA_PASS=", 1},
    {"woff", "", "AT+WIFI_OFF\r\n", 0},
    {"won", "", "AT+WIFI_ON\r\n", 0},
    {"nvs_rst", "", "AT+NVS_RST\r\n", 0},
    {"wmode", "<0 / 1 / 2 / 3>", "AT+WIFI_MODE=", 1},
    {"wap_chan", "<Number>", "AT+WAP_CHAN=", 1},
    {"wap_auth", "<Number as AUTH_TYPE>", "AT+WAP_AUTH=", 1},
    {"wrst", "", "AT+WIFI_RST\r\n", 0},
```

### Issues/PRs references
none

2022-02-25 19:27 UTC, luisan00 commented
AT commads for the shell should be more human readable, for example
`won` -> `wifi_on`
`woff` -> `wifi_off`
Also keep in mind some commands will set a value (=) but others may query for a value or status (?)

2022-02-25 19:30 UTC, luisan00 commented on examples/at_uart/main.c
> +#include "thread.h"
why this?

2022-02-25 19:31 UTC, luisan00 commented on examples/at_uart/main.c
> +typedef struct t_at_list {
this name is not aligned with our CC

2022-02-25 19:31 UTC, luisan00 commented on examples/at_uart/main.c
> +} tAT_LIST;
and this too

2022-02-25 19:32 UTC, luisan00 commented on examples/at_uart/main.c
> +enum AT_COUNT {
name unaligned with our CC

2022-02-25 19:33 UTC, luisan00 commented on examples/at_uart/main.c
> +}
this is taken from an older example, remove it or adjust it for your requirements

2022-02-25 19:34 UTC, luisan00 commented on examples/at_uart/main.c
> +#define MAX_SENTENCE_SIZE 128
this must be adjusted or deleted

2022-02-25 19:35 UTC, luisan00 commented on examples/at_uart/main.c
> +char uart_buff[MAX_SENTENCE_SIZE] = {0};
change it according your requirements or delete it if not used

2022-02-25 19:38 UTC, luisan00 commented on examples/at_uart/main.c
> +        uart_poweroff(AT_UART);
this may cause some unwanted behaviour

2022-02-25 19:38 UTC, luisan00 commented on examples/at_uart/main.c
> +        uart_poweroff(AT_UART);
this may cause some unwanted behaviour

2022-02-25 19:40 UTC, luisan00 requested changes
starting with rounds of reviews xD

2022-03-02 10:26 UTC, luisan00 commented on .clang-format
> +SortIncludes:    false
this should be into another PR, this is: 
> example: at_uart #155

2022-03-02 10:27 UTC, luisan00 commented on firmware/libs/at_commands_uart/Makefile
> +APPLICATION = at_uart
1.- Wrong makefile
2.- this should be into another PR, this PR name is: 
> example: at_uart #155

2022-03-02 10:29 UTC, luisan00 requested changes
another round xD

2022-03-03 15:41 UTC, eduazocar commented on examples/at_uart/Makefile
> +include $(RIOTBASE)/Makefile.include
add EOF

2022-03-07 13:40 UTC, eduazocar approved these changes
Well this look good for me :+1:

2022-03-07 23:45 UTC, closed without merging