Firmware storage
Mesh4all/m4a-firmware pull request #171
Opened 2022-03-14 23:47 UTC by xkevin190

### Contribution description

In this PR, an implementation was created to save in the flash memory of the boards at a higher level, strings no larger than 64 bytes can be saved, as well as u8 numbers, and delete at will.

### Testing procedure

   A way to test from riot has not been implemented yet but you cant test this module like so:
  
  1) execute `m4a_mtd_init`
  2) to write execute  `mtd_write_string` or `mtd_write_u8`
  3) to write execute  `mtd_read_string` or `mtd_read_u8`
  4) to delete use `m4a_mtd_erase`

### Issues/PRs references

this PR fixes #170

2022-03-15 11:08 UTC, luisan00 commented
Resolve static test and build issues before request for review

2022-03-15 19:50 UTC, luisan00 commented on firmware/Makefile
> +USEMODULE += storage
this is not part of the module, i think it should not be here, what's you think about it?

2022-03-15 19:52 UTC, luisan00 commented on firmware/Makefile
> +USEMODULE += storage
anyway modules should dynamically added so this will change in a near future

2022-03-15 19:53 UTC, luisan00 commented on firmware/default_params.h
> + */
use the correct group

2022-03-15 19:56 UTC, luisan00 commented on firmware/default_params.h
> +#define ADDRESS3       (uint32_t)flashpage_addr(LAST_AVAILABLE_PAGE - 2)
this should be inline-documented, what about running locally doxygen ? xD

2022-03-15 19:57 UTC, luisan00 commented on firmware/main.c
fix this

2022-03-15 19:58 UTC, luisan00 commented on firmware/sys/storage/include/storage.h
> + */
wrong doxygen header format

2022-03-15 20:00 UTC, luisan00 commented on firmware/sys/storage/include/storage.h
> + * @return int
what is the purpose of this return?

2022-03-15 20:13 UTC, luisan00 commented on firmware/sys/storage/storage.c
> +        printf("Error to read in mtd \n");
this should return some type of errno, i think, right?

2022-03-15 20:21 UTC, luisan00 commented on firmware/sys/storage/storage.c
> +    }
un-handled error

2022-03-15 20:25 UTC, luisan00 requested changes
good job :+1:  only some changes are required i think

2022-03-16 13:43 UTC, CyberWolf-Az commented on firmware/sys/storage/storage.c
> +    uint8_t buf_read[len];
This represent an static array so, could be the same that 
```suggestion
    uint8_t buf_read[MAX_SIZE_STORAGE +  3]; // Represent sizeof buff_empty array //
    /* Option 2 */
    uint8_t buf_read[19];
```

2022-03-16 13:44 UTC, xkevin190 commented on firmware/default_params.h
> + * @name    defaults params for wifi
you raight xD

2022-03-16 13:49 UTC, CyberWolf-Az commented on firmware/sys/storage/storage.c
> +    char buf_read[_len];
buf_empty won't be used, only represent 3 empty bytes, used to expand the buf_read

2022-03-16 13:53 UTC, luisan00 commented on firmware/default_params.h
> + * @ingroup     default-params
should be in the doxygen group firmware, what do you think @xkevin190 ?

2022-03-16 13:54 UTC, luisan00 commented on firmware/default_params.h
> + * @name this is the number of pages that we can write
```suggestion
 * @brief this is the number of pages that we can write
```

2022-03-16 13:54 UTC, luisan00 commented on firmware/default_params.h
> + *
```suggestion
```

2022-03-16 13:56 UTC, luisan00 commented on firmware/doc.txt
> +
copy paste without review

2022-03-16 13:57 UTC, luisan00 requested changes
one more time please xD

2022-03-16 14:15 UTC, CyberWolf-Az commented on firmware/sys/storage/storage.c
> +    int ret = mtd_write(dev, buf, key, sizeof(buf));
strlen() functions could be protect to send empty or null characters, that it's no supported by sizeof().

2022-03-16 15:36 UTC, luisan00 commented on firmware/default_params.h
> + * @name    defaults params for the firmware
```suggestion
 * @name    Defaults params for the m4a firmware
```

2022-03-16 15:37 UTC, luisan00 commented on firmware/main.c
> +}
```suggestion
}

```

2022-03-16 15:39 UTC, luisan00 requested changes
minimal changes :+1: , if you want change it, squash it and set the name of the commit

2022-03-16 15:45 UTC, CyberWolf-Az requested changes
Everything looks good for me, but needs a little bit more, make the last requests of @luisan00 and me...

2022-03-16 15:52 UTC, luisan00 approved these changes

2022-03-16 16:04 UTC, merged