Feature/test batery
Mesh4all/m4a-firmware pull request #173
Opened 2022-03-18 12:45 UTC by xkevin190

### Contribution description

### Testing procedure

the module was added and tested the library to do unit tests of riot, for the first tests all the storage module of the firmware was tested.

### Issues/PRs references

cd test/storage

make BOARD="your_board" flash term

2022-03-23 22:40 UTC, eduazocar commented on tests/Makefile.tests_common
>  DEVELHELP ?= 1
Add EOF

2022-03-23 22:43 UTC, eduazocar commented on tests/storage/tests/01-run.py
> +
I know that it is python, but you have an empty line

2022-03-23 22:47 UTC, eduazocar reviewed
Everything looks good for me, only make a little changes :+1:

2022-03-26 11:34 UTC, luisan00 requested changes
1. static test errors should be fixed before to continue.
2. error compiling for `m4a-24g` and possibly `m4a-mb` (not tested)

2022-03-28 11:25 UTC, luisan00 commented
test command **is**: 
```make BOARD="your_board" flash test```

2022-03-28 13:44 UTC, RocioRojas commented on tests/storage/main.c
remove blank line

2022-03-28 13:46 UTC, RocioRojas commented on tests/Makefile.tests_common
>  DEVELHELP ?= 1
add EOF

2022-03-28 14:26 UTC, RocioRojas approved these changes

2022-03-28 14:29 UTC, luisan00 commented
Squash it please

2022-03-28 14:34 UTC, luisan00 commented
Looks good, wait for static test and ready

2022-03-28 14:35 UTC, luisan00 approved these changes
Ready to go ahead

2022-03-28 14:36 UTC, merged