test: added test to udp_client
Mesh4all/m4a-firmware pull request #192
Opened 2022-03-29 11:54 UTC by xkevin190

### Contribution description

Added test to unique id component.

### Testing procedure

cd test/udp_client

make BOARD="your_board" flash test

### Issues/PRs references

2022-03-30 10:34 UTC, luisan00 commented
:clap: request :clap: review :clap: only :clap: when :clap: all :clap: test :clap: are :clap: green

2022-03-30 10:35 UTC, luisan00 requested changes
:clap: request :clap: review :clap: only :clap: when :clap: all :clap: test :clap: are :clap: green

2022-03-31 17:17 UTC, eduazocar commented
Please change description to english

2022-03-31 18:13 UTC, eduazocar commented on tests/udp_client/main.c
> + * @brief       storage file
Change reference to Test_udp_client

2022-03-31 21:59 UTC, eduazocar reviewed
Everything looks good for me, do squash to approve this

2022-03-31 22:17 UTC, eduazocar approved these changes
Go ahead :+1:

2022-04-01 06:10 UTC, RocioRojas commented on tests/udp_client/main.c
> +#include "shell.h"
remove includes: shell, shell_commands, msg, xtimer, board

2022-04-01 06:15 UTC, RocioRojas commented on tests/udp_client/doc.txt
>  to test only C code"
to test only C code:

2022-04-01 15:39 UTC, eduazocar commented on tests/udp_client/main.c
> +
What do you need the xtimer library?

2022-04-01 15:39 UTC, eduazocar commented on tests/udp_client/main.c
> +
You have two consecutive empty lines

2022-04-01 15:42 UTC, RocioRojas commented on tests/udp_client/main.c
> +#include "shell.h"
Removed incluedes: shell, shell_commands, msg, xtimer, board

2022-04-01 16:07 UTC, xkevin190 commented on tests/udp_client/main.c
> +
i remove it

2022-04-01 16:10 UTC, xkevin190 commented on tests/udp_client/main.c
> +
removed

2022-04-01 16:17 UTC, eduazocar reviewed
Good, do squash to approve this

2022-04-01 17:34 UTC, eduazocar approved these changes
Good :+1: This is approved

2022-04-01 17:52 UTC, luisan00 approved these changes
👍

2022-04-01 17:54 UTC, merged