sys/docs: at_client documentation
Mesh4all/m4a-firmware pull request #205
Opened 2022-03-30 15:39 UTC by RocioRojas

### Contribution description
Documentation for the at_client module was written

### Testing procedure
Look at firmware/sys/at_client/doc.txt

### Issues/PRs references

2022-03-30 20:29 UTC, luisan00 commented on firmware/sys/at_client/doc.txt
> +
Define an unique doxygen group for this component

2022-03-30 20:31 UTC, luisan00 commented on firmware/sys/at_client/doc.txt
> +# What goes here?
1st level title should be unique for a component.

2022-03-30 20:33 UTC, luisan00 requested changes
Some changes needs to be addressed

2022-03-30 21:14 UTC, luisan00 commented on firmware/sys/at_client/include/at_client.h
> + * @ingroup     sys
This should be something like `AT client` but not sys

2022-03-31 17:16 UTC, eduazocar commented on firmware/sys/at_client/doc.txt
> +
or something like this
```suggestion
@defgroup at_uart_firm
```
*** Be careful to the group defined is not used in wifi-subsys ***

2022-04-01 15:51 UTC, eduazocar reviewed
Everything here looks good for me, do squash :+1:

2022-04-01 18:02 UTC, eduazocar approved these changes
Approved :+1:

2022-04-01 19:59 UTC, eduazocar approved these changes
:+1:

2022-04-01 21:24 UTC, xkevin190 approved these changes

2022-04-04 12:42 UTC, luisan00 approved these changes
good job,going ahead!

2022-04-04 12:42 UTC, merged