added doc.txt to ds18_sensor test
Mesh4all/m4a-firmware pull request #208
Opened 2022-04-01 00:05 UTC by xkevin190

### Contribution description

the doc.txt was added to the ds18 sensor test module where it is explained how to use it and how to execute it

2022-04-01 11:41 UTC, luisan00 requested changes
reviewed

2022-04-01 11:41 UTC, luisan00 commented on tests/ds18/doc.txt
> +@defgroup ds18_test DS18 test mdoule
what? :smile:

2022-04-01 11:41 UTC, luisan00 commented on tests/ds18/doc.txt
> +To test the code from python:
same

2022-04-01 11:41 UTC, luisan00 commented on tests/ds18/doc.txt
> +to test only C code"
same

2022-04-01 15:56 UTC, eduazocar commented on tests/ds18/doc.txt
> +you must also add the gipio where your board will be connected in the test init function in the main.c file
gpio

2022-04-01 15:57 UTC, eduazocar reviewed
Fix some misspellings words

2022-04-01 19:19 UTC, eduazocar commented on tests/ds18/doc.txt
> +@defgroup ds18_test DS18_SENSOR test mdoule
Still having the same mistake reviewed by @luisan00

2022-04-01 19:20 UTC, eduazocar commented on tests/ds18/doc.txt
> +@defgroup ds18_test DS18_SENSOR test mdoule
Refers to test module

2022-04-01 22:06 UTC, eduazocar commented on tests/storage/doc.txt
> + */
Why this document is includes?

2022-04-01 22:07 UTC, eduazocar reviewed
Let's go, only a simple corrections, and that it's all

2022-04-04 12:48 UTC, luisan00 commented on tests/ds18/doc.txt
> +@defgroup ds18_test DS18_SENSOR test module
why capital words? and why underscore between words?

2022-04-04 12:49 UTC, luisan00 requested changes
one more please

2022-04-04 13:38 UTC, luisan00 commented on tests/storage/doc.txt
> + */
looks a copy paste issue xD

2022-04-04 15:21 UTC, eduazocar approved these changes
Good job :+1:

2022-04-04 15:22 UTC, luisan00 approved these changes
👍

2022-04-04 15:30 UTC, merged