doc: added doc.txt to storage test
Mesh4all/m4a-firmware pull request #210
Opened 2022-04-01 01:08 UTC by xkevin190

### Contribution description

he doc.txt was added to the serialization test module where it is explained how to execute it

2022-04-01 06:18 UTC, RocioRojas commented on tests/storage/doc.txt
> +to test only C code"
to test only C code:

2022-04-01 11:29 UTC, luisan00 commented on tests/storage/doc.txt
> +
define the oxygen group where this test is

2022-04-01 11:38 UTC, luisan00 requested changes
reviewed!

2022-04-01 11:38 UTC, luisan00 commented on tests/storage/doc.txt
> +To test the code from python:
Modes are interactive or automatic test

2022-04-01 11:38 UTC, luisan00 commented on tests/storage/doc.txt
> +to test only C code"
anyway the `c` code is tested both ways

2022-04-01 21:59 UTC, eduazocar approved these changes
Good job :+1:

2022-04-04 12:42 UTC, luisan00 approved these changes

2022-04-04 12:51 UTC, merged