wifi-subsys: some modifications
Mesh4all/m4a-firmware pull request #240
Opened 2022-04-28 15:31 UTC by xkevin190

### Contribution description

modifications were made to be able to wifi-subsys so that when sensor data arrive they are sent to the remote server changes were also added to the https client to send cbor values

### Testing procedure

### Issues/PRs references

2022-04-28 17:14 UTC, RocioRojas commented on wifi-subsys/components/uart/src/subsys_uart.c
> +    memcpy(request.url, "https://cloud.mesh4all.org/?a=1&b=2&c=3",
Change -> a=1&b=2&c=3

2022-04-28 17:14 UTC, RocioRojas commented on wifi-subsys/components/uart/src/subsys_uart.c
> +           sizeof("https://cloud.mesh4all.org/?a=1&b=2&c=3"));
change https://cloud.mesh4all.org/?a=1&b=2&c=3

2022-04-29 03:06 UTC, eduazocar commented on wifi-subsys/components/protocols/src/httpsclient.h
> +#define HTTPS_CONTENT_CBOR "application/cbor"
Remove this, this it's not working in https_protocol component

2022-04-29 03:19 UTC, eduazocar requested changes

2022-04-29 03:19 UTC, eduazocar commented on wifi-subsys/components/uart/src/subsys_uart.c
> +#include "httpsclient.h"
In the module or component file, if you are including others modules, you are breaking their independency, I refers to use uart_at, you will need to load component/tools and component/protocols

2022-04-29 18:51 UTC, RocioRojas commented
Good job!, only one change, the name of PR.

2022-04-30 03:23 UTC, eduazocar approved these changes

2022-05-02 12:08 UTC, RocioRojas approved these changes

2022-05-02 12:09 UTC, merged