Tools: Socket_client PC to a m4a-device
Mesh4all/m4a-firmware pull request #249
Opened 2022-05-09 05:34 UTC by eduazocar

### Contribution description

This is an implementation of vaina source code, The objective of this PR is design an udp client to connect with an device and send it a NIB_ADD request or a NIB_DEL, this device will response with an ACK if the request was received correctly, if the request was wrong received, the device should response with an  NACK.

These Pr contains some structures to gives the elements required to this process, refering an client by an interface, example:
```sh
enp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.119  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::bef4:bb4a:f786:e805  prefixlen 64  scopeid 0x20<link>
        ether ce:e0:4c:2a:25:ba  txqueuelen 1000  (Ethernet)
        RX packets 404502  bytes 274362830 (274.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3763595  bytes 294018792 (294.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 34999  bytes 4438649 (4.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34999  bytes 4438649 (4.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
the `enp2s0` refers to an ethernet interface, that will stablished the communication between both systems.
 
 

### Testing procedure

move on to the dist/tools/socket_client to run the following program:
```
gcc client.c -o client
./client
```

### Issues/PRs references

2022-05-09 10:49 UTC, luisan00 requested changes
1.- The tool name is ambiguous 
2.- What's the purpose of a command in this tool?

2022-05-09 10:49 UTC, luisan00 commented on dist/tools/socket_client/socket_msg.h
> +#define MSG_NACK 4
For a better understanding this should be an `enum`

2022-05-13 13:12 UTC, luisan00 requested changes
nice job !! :100: 
just documentation and aesthetics by now

2022-05-13 13:12 UTC, luisan00 commented on firmware/network/chamos/include/chamos.h
> +    MSG_NIB_DEL = 3,  /**< Delete entry from NIB */
wrong inline documentation format

2022-05-13 13:12 UTC, luisan00 commented on firmware/network/chamos/include/chamos.h
> +    ipv6_addr_t ip;  /**< IP address */
wrong inline documentation format

2022-05-13 13:20 UTC, eduazocar reviewed
Good, only has a little doc corrections and format corrections :+1:

2022-05-13 13:20 UTC, eduazocar commented on firmware/network/chamos/include/chamos.h
> + * @param port     [in]  port
Fix format nteif to netif

2022-05-13 13:22 UTC, eduazocar commented on dist/tools/chamoc/chamoc_msg.c
> +uint8_t craft_seqno(chamos_client_t *client) { client->seqno += 1; }
Sorry that was generated by the clang-format, i will fixed it

2022-05-13 13:34 UTC, xkevin190 requested changes

2022-05-13 13:34 UTC, xkevin190 commented on dist/tools/chamoc/doc.txt
> +@ingroup  network
this module is not part of the firmware, please add one correct group.

2022-05-13 14:00 UTC, xkevin190 commented on dist/tools/chamoc/chamoc_msg.c
> +    uint8_t strbuff[19] = {msg.message, msg.seqno, msg.prefix};
```suggestion
    uint8_t strbuff[sizeof(chamoc_message_t)] = {msg.message, msg.seqno, msg.prefix};
```

2022-05-13 14:08 UTC, eduazocar commented on dist/tools/chamoc/nib.c
> +    if (msg_type == 2 || 3) {
It's the same

2022-05-13 15:19 UTC, xkevin190 requested changes

2022-05-13 15:19 UTC, xkevin190 commented on firmware/network/chamos/chamos.c
> +        memcpy(&chamos_msg->ip, &buffer[3], sizeof(ipv6_addr_t));
verify the address is correct before doing this

2022-05-13 15:19 UTC, xkevin190 commented on firmware/network/chamos/chamos.c
> +        memcpy(&chamos_msg->ip, &buffer[3], sizeof(ipv6_addr_t));
verify the address is correct before doing this

2022-05-16 18:53 UTC, luisan00 requested changes
well done. almost finished!

2022-05-16 18:53 UTC, luisan00 commented on dist/tools/chamoc/start_network.sh
> +
```suggestion
```

2022-05-16 18:53 UTC, luisan00 commented on tests/chamoc_server/run.sh
> +fi
```suggestion
fi

```

2022-05-16 19:53 UTC, xkevin190 approved these changes

2022-05-16 20:04 UTC, luisan00 approved these changes
well dona!! going ahead!! :+1:

2022-05-16 20:05 UTC, merged