sys/uniqueid: Fixed rendundancy code and dependencies to multi support
Mesh4all/m4a-firmware pull request #297
Opened 2022-07-06 20:40 UTC by eduazocar

### Contribution description
This Pr add support to uniqueid in native boards, and use the `periph_hwrng` to provide a random `uint32_t` value. So the use of netopt `NETOPT_RANDOM`will give it to the boards with radio integrated.  The radio module will be loaded only when the board has an radio interface, if this interface doesn't exist, will use the `periph_hwrng` to provide an random value of uniqueid. Also removes the uniqueid dependency from the radio module, this itself doesn't need pre-load to use it.

### Testing procedure
in the section uniqueid you have to configurate to the random, for see the random number generator running.
```
make menuconfig -C tests/uniqueid flash term
```

### Issues/PRs references
Fixes #293

2022-07-07 13:03 UTC, RocioRojas requested changes

2022-07-07 13:16 UTC, RocioRojas requested changes

2022-07-07 14:02 UTC, eduazocar commented on tests/uniqueid/whitelist
> +m4a-24g
that it's only a register, i could remove it

2022-07-07 14:02 UTC, eduazocar commented on tests/uniqueid/main.c
> + * @author  eduazocar <eduazocarv@gmail.com>
When I run native this throw an error

2022-07-08 00:23 UTC, RocioRojas commented
Looks good for me, do squash!!

2022-07-08 16:24 UTC, RocioRojas commented on tests/uniqueid/main.c
> +    printf("Binary data printed\n");
Please put  ```\n \n Binary data printed\n```

2022-07-08 18:37 UTC, RocioRojas approved these changes

2022-07-08 18:37 UTC, merged