boards: merge repo. boards as folder
Mesh4all/m4a-firmware pull request #70
Opened 2022-01-06 16:21 UTC by luisan00

### Contribution description
First step in the groupping repositories task

### Testing procedure
make should work with m4a boards:

```sh
make BOARD=m4a-mb
```
or
```sh
make BOARD=m4a-24g
```
should build the firmware

### Issues/PRs references
#69

2022-01-06 19:08 UTC, eduazocar reviewed
Everything it's fine :+1:

2022-01-06 19:09 UTC, eduazocar approved these changes

2022-01-06 19:10 UTC, eduazocar commented
I see some warnings, from a group of files in example folder...

2022-01-07 03:48 UTC, eduazocar commented
squash to merge soon :+1:

2022-01-07 05:46 UTC, luisan00 commented
> squash to merge soon fireworks

Today should be ready to merge

2022-01-07 16:09 UTC, eduazocar requested changes

2022-01-08 10:25 UTC, luisan00 commented on boards/m4a-mb/include/board.h
> +#define LED0_PIN GPIO_PIN(PB, 30)                       /*!< LED0 is routed to pin PB30 in the MCU */
:+1:

2022-01-08 11:00 UTC, merged