examples: slipdev integration
Mesh4all/m4a-firmware pull request #87
Opened 2022-01-13 20:18 UTC by eduazocar

### Contribution description
This PR it's to add the slipdev example, to use the UART as net device.

### Testing procedure

### Issues/PRs references
fixes #85

2022-01-13 20:42 UTC, luisan00 commented on examples/esp32-wroom-32/slipdev/Makefile
> +APPLICATION = slipdev_test
```suggestion
APPLICATION = slipdev_example
```

2022-01-13 21:55 UTC, luisan00 commented on examples/esp32-wroom-32/slipdev/main.c
> + * @ingroup     examples/esp32-wroom
```suggestion
 * @ingroup     examples_esp32-wroom
```
Why not the current form?

2022-01-13 21:56 UTC, luisan00 commented on examples/esp32-wroom-32/slipdev/main.c
> +
too many empty things

2022-01-13 21:57 UTC, luisan00 requested changes
good job man,  only some minor things

2022-01-13 22:03 UTC, luisan00 commented on examples/esp32-wroom-32/slipdev/slipdev_params.h
> + * @ingroup tests
i think this should be changed , i don't know if it fit in our documentation build system

2022-01-14 13:25 UTC, luisan00 commented on examples/esp32-wroom-32/slipdev/README.md
> +# Esp32-wroom examples
yeah, looks a mistake

2022-01-14 15:02 UTC, xkevin190 commented
looks good, but you not added the  EOF space of the end every file bro.

2022-01-14 15:04 UTC, xkevin190 commented
![Screen Shot 2022-01-14 at 11 03 09 AM](https://user-images.githubusercontent.com/37220428/149537208-9b155958-96c6-4ddc-aab6-5eaacb2d4aba.png)

missing EOF space

2022-01-14 15:04 UTC, xkevin190 commented
![Screen Shot 2022-01-14 at 11 03 19 AM](https://user-images.githubusercontent.com/37220428/149537320-806e5365-e5e1-4adc-b809-36ae95142d11.png)

missing EOF space

2022-01-14 15:06 UTC, xkevin190 requested changes

2022-01-14 15:06 UTC, xkevin190 commented on examples/esp32-wroom-32/slipdev/main.c
> +}
missing EOF space

2022-01-14 17:31 UTC, xkevin190 approved these changes

2022-01-14 19:59 UTC, luisan00 approved these changes

2022-01-14 19:59 UTC, luisan00 commented
Let's go ahead @eduazocar

2022-01-14 20:02 UTC, luisan00 commented
please squash before merge bro

2022-01-14 20:18 UTC, merged